#!/usr/bin/env bash
# shellcheck disable=SC2034,SC2086,SC2230,SC2009,SC2206,SC2062,SC2059,SC2229,SC2154,SC2162,SC2120

######################################
# User Variables - Change as desired #
# Leave as is if unsure              #
######################################


ASSETNAME="assetname"										            # Asset name - NO SPACES!
TOKENNAME="given name #001"										        # Token readable name
IMGLINK="ipfs://QmZohc2mLgsXDhF17DskrLdGraPKPmSVbefp5kXmT7WfuC"		    # ipfs link to img/art
CREATOR="Moshe Moshe"			                       					# Creator name
IGLINK="https://www.instagram.com/adararestakepool"				        # Instagram Link
base_addr="$(cat $CNODE_HOME/priv/wallet/nft/base.addr)"		     	# your base.addr file under nft wallet
asset_amount=10				                    						# amount to mint


